blank_issues_enabled: false
contact_links:
  - name: Documentación
    url: https://github.com/RenatoAntonioCL/genpy/blob/main/docs/CONTRIBUTING.md
    about: Lee la guía de contribución antes de abrir un issue
