#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# GenPy — lib/template.sh (v1.0.0-alpha)
#
# Template copying and variable injection engine.
#
# Bug fixed: the previous version stored the sed command in a string variable
# ("sed -i ''") and executed it as $sed_cmd "s/...". In Bash with
# set -euo pipefail this fails because the string with spaces does not expand
# as a command. Solution: _sed_inplace() wrapper function that abstracts the
# difference between macOS and Linux without needing eval.
# =============================================================================

# -----------------------------------------------------------------------------
# _sed_inplace  (internal function)
#
# Abstracts the sed -i difference between macOS (requires '' suffix) and Linux.
# Using this function instead of $sed_cmd eliminates the variable expansion bug.
#
# Arguments:
#   $1 — sed expression
#   $2 — file to modify
# -----------------------------------------------------------------------------
_sed_inplace() {
  local expression="$1"
  local file="$2"

  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "$expression" "$file"
  else
    sed -i "$expression" "$file"
  fi
}

# -----------------------------------------------------------------------------
# _generate_secret  (internal function)
#
# Generates a cryptographically secure random hexadecimal string.
# Uses openssl rand if available; falls back to /dev/urandom.
#
# Arguments:
#   $1 — bytes: number of random bytes (hex output will have twice as many chars)
# -----------------------------------------------------------------------------
_generate_secret() {
  local bytes="${1:-32}"
  if command -v openssl &>/dev/null; then
    openssl rand -hex "$bytes"
  else
    LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c "$((bytes * 2))"
  fi
}

# -----------------------------------------------------------------------------
# _inject_env_secrets  (internal function)
#
# Replaces {{SECRET_HEX_N}} markers in the .env with random values
# generated by _generate_secret. Then resolves cross-references of the
# {{VAR_NAME}} type (used e.g. in DATABASE_URL to reference
# the generated password).
#
# Arguments:
#   $1 — env_file: path to the .env to process
# -----------------------------------------------------------------------------
_inject_env_secrets() {
  local env_file="$1"
  [[ -f "$env_file" ]] || return 0

  local -A _secret_map
  local tmp generated=0
  tmp=$(mktemp)

  # Pass 1: generate secrets for each {{SECRET_HEX_N}}.
  # Stores the generated value in _secret_map keyed by variable name.
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ ^([A-Z_][A-Z0-9_]*)=.*\{\{SECRET_HEX_([0-9]+)\}\} ]]; then
      local var_name="${BASH_REMATCH[1]}"
      local bytes="${BASH_REMATCH[2]}"
      local secret
      secret=$(_generate_secret "$bytes")
      _secret_map["$var_name"]="$secret"
      line="${line//\{\{SECRET_HEX_${bytes}\}\}/$secret}"
      generated=1
    fi
    printf '%s\n' "$line"
  done < "$env_file" > "$tmp"

  # Pass 2: substitute cross-references {{VAR_NAME}} (e.g.: in DATABASE_URL).
  # Uses bash string substitution — ${#arr[@]} with empty arrays triggers
  # nounset in bash 5.3; the 'generated' flag avoids that path for blueprints without secrets.
  if [[ "$generated" -eq 1 ]]; then
    local content
    content=$(< "$tmp")
    for var_name in "${!_secret_map[@]}"; do
      content="${content//\{\{${var_name}\}\}/${_secret_map[$var_name]}}"
    done
    printf '%s\n' "$content" > "$env_file"
    chmod 600 "$env_file"   # .env contains real secrets: owner-read only
    local vars_list
    vars_list=$(printf '%s, ' "${!_secret_map[@]}")
    echo "🔐 Secrets generated in .env: ${vars_list%, }"
  else
    mv "$tmp" "$env_file"
    chmod 600 "$env_file"   # restrictive permissions also for .env without generated secrets
    return 0
  fi

  rm -f "$tmp"
}

# -----------------------------------------------------------------------------
# copy_template
#
# Copies the chosen blueprint template to the destination directory and injects
# the project name into all relevant files.
#
# Arguments:
#   $1 — template_dir:   absolute path to the template (e.g.: .../templates/web-fastapi-postgres)
#   $2 — target_dir:     ABSOLUTE path where the project will be created
#   $3 — project_name:   project name to replace {{PROJECT_NAME}}
#
# Bug fixed: the caller must now pass target_dir as an absolute path.
# wizard.sh uses "$(pwd)/$PROJECT_NAME" to ensure this.
# -----------------------------------------------------------------------------
copy_template() {
  local template_dir="$1"
  local target_dir="$2"
  local project_name="$3"

  [[ -d "$template_dir" ]] || { echo "Template not found: $template_dir" >&2; return 1; }

  echo "📁 Copying template from $template_dir to $target_dir..."
  mkdir -p "$target_dir"

  # Copies files (respects Model A: Dockerfile at root / Model B: in backend/)
  rsync -a --delete --exclude='.git' --exclude='.DS_Store' --exclude='__pycache__' \
    "$template_dir/" "$target_dir/"

  if [[ -z "$(ls -A "$target_dir")" ]]; then
    echo "Template copied empty: $template_dir" >&2
    return 1
  fi

  echo "✅ Structure copied."

  # --- NEW: Variable injection ---
  echo "🔧 Injecting project name: $project_name"

  # Search only text files to avoid corrupting binaries
  while IFS= read -r file; do
    _sed_inplace "s/{{PROJECT_NAME}}/$project_name/g" "$file"
  done < <(find "$target_dir" -type f \( \
    -name ".env" -o \
    -name "*.md" -o -name "docker-compose.yml" -o -name "Dockerfile" \
    -o -name "*.py" -o -name "*.sh" -o -name "*.go" -o -name "go.mod" \
    -o -name "package.json" -o -name "nest-cli.json" -o -name "tsconfig.json" \
    \))

  _inject_env_secrets "$target_dir/.env"

  local blueprint_toml="$target_dir/.genpy/blueprint.toml"
  if [[ -f "$blueprint_toml" ]]; then
    if ! _validate_blueprint_toml "$blueprint_toml"; then
      echo "Error: invalid blueprint.toml in the generated project." >&2
      return 1
    fi
    echo "✅ blueprint.toml validated."
  fi

  echo "✨ Setup complete."
}

# -----------------------------------------------------------------------------
# _validate_blueprint_toml  (internal function)
#
# Verifies that the copied blueprint.toml exists, is not empty, and contains
# the minimum fields required by the GenPy contract ([meta] section with
# language and version). Uses only grep/bash — no external dependencies.
#
# Arguments:
#   $1 — toml_file: path to the .genpy/blueprint.toml to validate
# Returns:
#   0 — valid and parseable
#   1 — invalid (prints reason to stderr)
# -----------------------------------------------------------------------------
_validate_blueprint_toml() {
  local toml_file="$1"

  if [[ ! -f "$toml_file" ]]; then
    echo "Error: blueprint.toml not found: $toml_file" >&2
    return 1
  fi

  if [[ ! -s "$toml_file" ]]; then
    echo "Error: blueprint.toml is empty: $toml_file" >&2
    return 1
  fi

  if ! grep -q '^\[meta\]' "$toml_file"; then
    echo "Error: blueprint.toml: missing [meta] section" >&2
    return 1
  fi

  if ! grep -qE '^version[[:space:]]*=' "$toml_file"; then
    echo "Error: blueprint.toml: missing version field" >&2
    return 1
  fi

  if ! grep -qE '^language[[:space:]]*=[[:space:]]*"(python|go|javascript|bash|infra)"' "$toml_file"; then
    echo "Error: blueprint.toml: language field missing or unknown value" >&2
    return 1
  fi

  return 0
}
